apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-py
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-py
  template:
    metadata:
      labels:
        app: hello-py
    spec:
      containers:
      - name: hello-py
        image: nandhutk/hellopy
        ports:
        - containerPort: 5000
